# theme: jekyll-theme-minimal



title: themetalogician
description: "The Four Noble Truths and The Ten Fold Path."
# baseurl: ""            # leave empty for root site
# url: "https://themetalogician.com"
# theme: minima
