name: Build search index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate search.json
        run: |
          import os, json, re

          pages = []
          for root, _, files in os.walk("."):
              for f in files:
                  if f.endswith(".md") and not f.startswith("README"):
                      path = os.path.join(root, f)
                      url = "/" + path.replace("./", "").replace("index.md","").replace(".md",".html")
                      with open(path, encoding="utf-8") as file:
                          text = file.read()
                      m = re.search(r'^#\s+(.+)', text, re.M)
                      title = m.group(1) if m else f.replace(".md","")
                      content = re.sub(r'\s+', ' ', text)[:500]
                      pages.append({"title": title, "url": url, "content": content})

          with open("search.json", "w", encoding="utf-8") as out:
              json.dump(pages, out, ensure_ascii=False, indent=2)
        shell: python

      - name: Commit and push search.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add search.json
          git commit -m "Update search.json" || echo "No changes"
          git push
